### ISSUE TITLE
Error trying to execute csd list command

### ISSUE THREAD

**Issue by mainakanyi** [justinlettau/cordova-sqlite-devtools#2] opened 2017-01-27 11:32 UTC
C:\xampp\htdocs\ionicLogin>csd list
{ Error: Command failed: adb shell "run-as com.ionicframework.ioniclogin429431 ls databases"
'adb' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'adb shell "run-as com.ionicframework.ioniclogin429431 ls databases"' }

C:\xampp\htdocs\ionicLogin>

**Comment by justinlettau** [comment] 2017-01-27 12:30
Duplicate of [#1](https://github.com/justinlettau/cordova-sqlite-devtools/issues/1)

**Closed by justinlettau** 2017-01-27 12:30 UTC

**Comment by mainakanyi** [comment] 2017-01-27 12:32
@justinlettau How re you doing? How can I solve this problem?  Best Regards
